# Generated by Django 3.1.7 on 2021-04-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0003_auto_20210310_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('from_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserToPostgre.group', to_field='number')),
            ],
        ),
    ]
