# Generated by Django 3.1.7 on 2021-04-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0004_auto_20210415_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_post', to='parserToPostgre.group', to_field='number'),
        ),
    ]
