# Generated by Django 3.1.7 on 2021-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0005_auto_20210415_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='domain',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
