# Generated by Django 3.1.7 on 2021-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0006_group_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('is_closed', models.BooleanField()),
                ('sex', models.CharField(max_length=5)),
                ('nickname', models.TextField()),
                ('domain', models.TextField()),
                ('city', models.TextField()),
                ('county', models.TextField()),
                ('photo', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='domain',
            field=models.TextField(default='hellyeahplay'),
        ),
    ]
