# Generated by Django 3.1.7 on 2021-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0007_auto_20210416_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slovo', models.TextField()),
                ('varianty', models.JSONField()),
            ],
        ),
    ]
