# Generated by Django 3.1.7 on 2021-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0008_badword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='slovo',
            field=models.TextField(unique=True),
        ),
    ]
