# Generated by Django 3.1.7 on 2021-04-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0010_baddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='baddata',
            name='text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='relate_text', to='parserToPostgre.comments', to_field='number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baddata',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baddata',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
