# Generated by Django 3.1.7 on 2021-04-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0011_auto_20210417_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='from_id',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
