# Generated by Django 3.1.7 on 2021-04-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0012_group_from_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baddata',
            name='text',
            field=models.TextField(),
        ),
    ]
