# Generated by Django 3.1.7 on 2021-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0013_auto_20210418_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
