# Generated by Django 3.1.7 on 2021-05-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0017_auto_20210521_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupListUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserToPostgre.user', to_field='user_id')),
            ],
        ),
    ]
