# Generated by Django 3.1.7 on 2021-05-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0019_auto_20210521_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_post', to='parserToPostgre.group', to_field='number'),
        ),
    ]
