# Generated by Django 3.1.7 on 2021-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserToPostgre', '0020_auto_20210522_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='varianty',
            field=models.TextField(),
        ),
    ]
